/**
 * UNIVERSAL PROTOCOL STANDARD COMPLIANCE HEADER
 * Evidence Library Database Export - Real Records from PostgreSQL
 * DEPRECATED: This file contains hardcoded vocabulary and violates the anti-hardcoding policy
 * USE INSTEAD: Dynamic database queries via API endpoints
 * 
 * @deprecated Use database-driven evidence library instead
 */

// DEPRECATED - DO NOT USE - VIOLATES ANTI-HARDCODING POLICY
// This array contains hardcoded equipment vocabulary and should not be used
// Use database-driven evidence library API instead: /api/evidence-library
export const EVIDENCE_LIBRARY_DATA_DEPRECATED: never[] = [
  {
    "id": 1,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "DATABASE_DRIVEN",
    "componentFailureMode": "Seal Leak",
    "equipmentCode": "PMP-CEN-001",
    "failureCode": "F-001",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Seal Pot Level, Leak Temp, DCS log",
    "aiOrInvestigatorQuestions": "When did leak start? Temp/vibration spike? Recent seal work?",
    "attachmentsEvidenceRequired": "Vibration plot, leak photo, maintenance",
    "rootCauseLogic": "Root: Seal aged/damaged. Contrib: Lubrication, misalignment."
  },
  {
    "id": 2,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Bearing Failure",
    "equipmentCode": "PMP-CEN-002",
    "failureCode": "F-002",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Bearing Temp, Oil Quality",
    "aiOrInvestigatorQuestions": "Spike in vibration? Overtemp? Oil degraded?",
    "attachmentsEvidenceRequired": "Vibration chart, oil analysis",
    "rootCauseLogic": "Root: Damaged bearing. Contrib: Oil contamination, overload."
  },
  {
    "id": 3,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Impeller Damage",
    "equipmentCode": "PMP-CEN-003",
    "failureCode": "F-003",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Flow Rate, Pressure, Inspection",
    "aiOrInvestigatorQuestions": "Flow drop? Evidence of damage?",
    "attachmentsEvidenceRequired": "Flow chart, photo, inspection",
    "rootCauseLogic": "Root: Broken/eroded impeller. Contrib: Cavitation, solids."
  },
  {
    "id": 4,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Casing Crack",
    "equipmentCode": "PMP-CEN-004",
    "failureCode": "F-004",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure, Leak, Inspection",
    "aiOrInvestigatorQuestions": "Leak from casing? Crack observed?",
    "attachmentsEvidenceRequired": "Inspection photo, pressure chart",
    "rootCauseLogic": "Root: Crack found. Contrib: Overpressure, casting defect."
  },
  {
    "id": 5,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Motor Overload",
    "equipmentCode": "PMP-CEN-005",
    "failureCode": "F-005",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Current, Motor Temp, Vibration",
    "aiOrInvestigatorQuestions": "Current/Temp spike? Trip event?",
    "attachmentsEvidenceRequired": "Current log, temp chart, trip log",
    "rootCauseLogic": "Root: Overload. Contrib: Binding, process upset."
  },
  {
    "id": 6,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Misalignment",
    "equipmentCode": "PMP-CEN-010",
    "failureCode": "F-006",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Coupling Inspection",
    "aiOrInvestigatorQuestions": "Abnormal vibration? Coupling wear?",
    "attachmentsEvidenceRequired": "Vibration plot, alignment report",
    "rootCauseLogic": "Root: Misalignment detected. Contrib: Foundation, installation."
  },
  {
    "id": 7,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Reciprocating",
    "componentFailureMode": "Valve Plate Failure",
    "equipmentCode": "PMP-REC-001",
    "failureCode": "F-010",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Discharge/Suction Pressure, Vibration",
    "aiOrInvestigatorQuestions": "Pressure drop? Vibration increase?",
    "attachmentsEvidenceRequired": "Pressure chart, vibration plot",
    "rootCauseLogic": "Root: Broken plate. Contrib: Fatigue, improper assembly."
  },
  {
    "id": 8,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Reciprocating",
    "componentFailureMode": "Piston Ring Wear",
    "equipmentCode": "PMP-REC-002",
    "failureCode": "F-011",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Flow, Lube Oil Consumption, Inspection",
    "aiOrInvestigatorQuestions": "Flow loss? Oil usage up?",
    "attachmentsEvidenceRequired": "Flow chart, oil log, inspection",
    "rootCauseLogic": "Root: Ring worn. Contrib: Poor lube, contamination."
  },
  {
    "id": 9,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Reciprocating",
    "componentFailureMode": "Crankshaft Failure",
    "equipmentCode": "PMP-REC-003",
    "failureCode": "F-012",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Motor Current, Inspection",
    "aiOrInvestigatorQuestions": "Vibration spike? Shaft inspection?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection report",
    "rootCauseLogic": "Root: Crank broken. Contrib: Fatigue, overload."
  },
  {
    "id": 10,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Reciprocating",
    "componentFailureMode": "Cylinder Liner Scoring",
    "equipmentCode": "PMP-REC-004",
    "failureCode": "F-013",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Pressure, Inspection",
    "aiOrInvestigatorQuestions": "Loss of compression? Liner damage?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection report",
    "rootCauseLogic": "Root: Scored liner. Contrib: Abrasive, contamination."
  },
  {
    "id": 11,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Rotary",
    "componentFailureMode": "Gear Wear",
    "equipmentCode": "PMP-ROT-001",
    "failureCode": "F-020",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Flow, Oil Debris",
    "aiOrInvestigatorQuestions": "Increased vibration? Metal in oil?",
    "attachmentsEvidenceRequired": "Vibration chart, oil debris report",
    "rootCauseLogic": "Root: Worn gear. Contrib: Poor oil."
  },
  {
    "id": 12,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Rotary",
    "componentFailureMode": "Housing Crack",
    "equipmentCode": "PMP-ROT-002",
    "failureCode": "F-021",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure, Visual Inspection",
    "aiOrInvestigatorQuestions": "Leak or crack in housing?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection photo",
    "rootCauseLogic": "Root: Crack found. Contrib: Fatigue, overpressure."
  },
  {
    "id": 13,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Centrifugal",
    "componentFailureMode": "Surge Event",
    "equipmentCode": "COM-CEN-001",
    "failureCode": "F-100",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Discharge Pressure, Flow, Vibration",
    "aiOrInvestigatorQuestions": "Any surge trips or oscillations?",
    "attachmentsEvidenceRequired": "Trend chart, trip log",
    "rootCauseLogic": "Root: Surge confirmed. Contrib: Controller malfunction."
  },
  {
    "id": 14,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Centrifugal",
    "componentFailureMode": "Seal Oil System Fault",
    "equipmentCode": "COM-CEN-002",
    "failureCode": "F-101",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Lube Oil Pressure/Temp, Alarm Log",
    "aiOrInvestigatorQuestions": "Seal oil pressure drop? Alarms prior?",
    "attachmentsEvidenceRequired": "Alarm log, trend chart",
    "rootCauseLogic": "Root: Pressure drop, alarms. Contrib: Pump trip, filter blocked."
  },
  {
    "id": 15,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Centrifugal",
    "componentFailureMode": "Rotor Rub",
    "equipmentCode": "COM-CEN-003",
    "failureCode": "F-102",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Bearing Temp, Inspection",
    "aiOrInvestigatorQuestions": "High vibration? Rotor contact?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection report",
    "rootCauseLogic": "Root: Rub confirmed. Contrib: Misalignment, overtemp."
  },
  {
    "id": 16,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Reciprocating",
    "componentFailureMode": "Cylinder Leak",
    "equipmentCode": "COM-REC-001",
    "failureCode": "F-110",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Cylinder Pressure, Lube Oil Temp",
    "aiOrInvestigatorQuestions": "Oil temp rise? Reduced pressure?",
    "attachmentsEvidenceRequired": "Pressure chart, oil temp log",
    "rootCauseLogic": "Root: Seal/ring worn. Contrib: Poor lube."
  },
  {
    "id": 17,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Reciprocating",
    "componentFailureMode": "Valve Failure",
    "equipmentCode": "COM-REC-002",
    "failureCode": "F-111",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Suction/Discharge Pressure, Vibration",
    "aiOrInvestigatorQuestions": "Pressure drop? Abnormal noise/vibration?",
    "attachmentsEvidenceRequired": "Pressure/vibration chart, inspection log",
    "rootCauseLogic": "Root: Valve stuck/broken, pressure drop. Contrib: Fouling."
  },
  {
    "id": 18,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Compressors",
    "subtype": "Reciprocating",
    "componentFailureMode": "Crosshead Pin Wear",
    "equipmentCode": "COM-REC-003",
    "failureCode": "F-112",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Oil Analysis, Inspection",
    "aiOrInvestigatorQuestions": "Excessive wear metals in oil?",
    "attachmentsEvidenceRequired": "Oil report, inspection log",
    "rootCauseLogic": "Root: Pin worn. Contrib: Lube breakdown, overload."
  },
  {
    "id": 19,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Turbines",
    "subtype": "Gas",
    "componentFailureMode": "Blade Erosion",
    "equipmentCode": "TUR-GAS-001",
    "failureCode": "F-200",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Exhaust Temp, Vibration, Power Output",
    "aiOrInvestigatorQuestions": "Temp rise? Power loss? Vibration?",
    "attachmentsEvidenceRequired": "Vibration chart, inspection report",
    "rootCauseLogic": "Root: Blade damage. Contrib: Fouling, particles. Ruled out: Blades OK."
  },
  {
    "id": 20,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Turbines",
    "subtype": "Gas",
    "componentFailureMode": "Bearing Overheating",
    "equipmentCode": "TUR-GAS-002",
    "failureCode": "F-201",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Bearing Temp, Vibration",
    "aiOrInvestigatorQuestions": "Bearing temp spike? Vibration increase?",
    "attachmentsEvidenceRequired": "Temp chart, vibration plot",
    "rootCauseLogic": "Root: Overheat. Contrib: Lube issue. Ruled out: Temp normal."
  },
  {
    "id": 21,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Turbines",
    "subtype": "Gas",
    "componentFailureMode": "Combustion Instability",
    "equipmentCode": "TUR-GAS-003",
    "failureCode": "F-202",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Combustion Pressure, Flame Pattern",
    "aiOrInvestigatorQuestions": "Pressure pulsation? Abnormal flame sensor reading?",
    "attachmentsEvidenceRequired": "Pressure trend, flame pattern log",
    "rootCauseLogic": "Root: Instability. Contrib: Fuel variation. Ruled out: Steady operation."
  },
  {
    "id": 22,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Turbines",
    "subtype": "Steam",
    "componentFailureMode": "Steam Leak",
    "equipmentCode": "TUR-STM-001",
    "failureCode": "F-210",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Steam Flow, Pressure, Inspection",
    "aiOrInvestigatorQuestions": "Steam seen/visible? Pressure drop?",
    "attachmentsEvidenceRequired": "Inspection report, pressure chart",
    "rootCauseLogic": "Root: Leak detected. Contrib: Gasket failure. Ruled out: No leak."
  },
  {
    "id": 23,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Turbines",
    "subtype": "Steam",
    "componentFailureMode": "Gland Packing Failure",
    "equipmentCode": "TUR-STM-002",
    "failureCode": "F-211",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Gland Seal Steam Flow, Temp",
    "aiOrInvestigatorQuestions": "Gland seal steam increase? Overheating?",
    "attachmentsEvidenceRequired": "Steam flow chart, temp log",
    "rootCauseLogic": "Root: Packing worn. Contrib: Misalignment. Ruled out: No temp rise."
  },
  {
    "id": 24,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fans/Blowers",
    "subtype": "Centrifugal",
    "componentFailureMode": "Impeller Imbalance",
    "equipmentCode": "FAN-CEN-001",
    "failureCode": "F-900",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Speed, Flow",
    "aiOrInvestigatorQuestions": "High vibration? Imbalance found?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection log",
    "rootCauseLogic": "Root: Imbalance confirmed. Contrib: Material buildup. Ruled out: Balanced."
  },
  {
    "id": 25,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fans/Blowers",
    "subtype": "Centrifugal",
    "componentFailureMode": "Bearing Wear",
    "equipmentCode": "FAN-CEN-002",
    "failureCode": "F-901",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Bearing Temp, Vibration",
    "aiOrInvestigatorQuestions": "Temp rise? Vibration up?",
    "attachmentsEvidenceRequired": "Temp chart, vibration plot",
    "rootCauseLogic": "Root: Bearing worn. Contrib: Over-greasing. Ruled out: Normal readings."
  },
  {
    "id": 26,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fans/Blowers",
    "subtype": "Axial",
    "componentFailureMode": "Blade Crack",
    "equipmentCode": "FAN-AXL-001",
    "failureCode": "F-910",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Inspection, Noise",
    "aiOrInvestigatorQuestions": "Abnormal noise? Crack in inspection?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection photo",
    "rootCauseLogic": "Root: Blade cracked. Contrib: Fatigue, corrosion. Ruled out: Blade intact."
  },
  {
    "id": 27,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Agitators/Mixers",
    "subtype": "Side Entry",
    "componentFailureMode": "Shaft Seal Leak",
    "equipmentCode": "AGT-SID-001",
    "failureCode": "F-950",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Temp, Visual Inspection, Vibration",
    "aiOrInvestigatorQuestions": "Seal area hot? Leak seen?",
    "attachmentsEvidenceRequired": "Temp chart, inspection log",
    "rootCauseLogic": "Root: Seal damaged. Contrib: Pressure, wear. Ruled out: Seal good."
  },
  {
    "id": 28,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Agitators/Mixers",
    "subtype": "Top Entry",
    "componentFailureMode": "Coupling Failure",
    "equipmentCode": "AGT-TOP-001",
    "failureCode": "F-960",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Motor Current, Inspection",
    "aiOrInvestigatorQuestions": "Coupling noise? Slippage?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection report",
    "rootCauseLogic": "Root: Failed coupling. Contrib: Misalignment. Ruled out: Coupling OK."
  },
  {
    "id": 29,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Heat Exchangers",
    "subtype": "Shell & Tube",
    "componentFailureMode": "Tube Leak",
    "equipmentCode": "HEX-SHT-001",
    "failureCode": "F-500",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure Drop, Fluid Analysis, Inspection",
    "aiOrInvestigatorQuestions": "Pressure drop? Cross-leakage in fluid?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection photo",
    "rootCauseLogic": "Root: Tube leak. Contrib: Corrosion, vibration. Ruled out: Tubes sound."
  },
  {
    "id": 30,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Heat Exchangers",
    "subtype": "Shell & Tube",
    "componentFailureMode": "Tube Fouling",
    "equipmentCode": "HEX-SHT-002",
    "failureCode": "F-501",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Pressure Drop, Temp Diff, Inspection",
    "aiOrInvestigatorQuestions": "High dP? Temp change? Visual fouling?",
    "attachmentsEvidenceRequired": "Pressure/temperature chart, inspection",
    "rootCauseLogic": "Root: Severe fouling. Contrib: Water quality. Ruled out: Clean tubes."
  },
  {
    "id": 31,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Heat Exchangers",
    "subtype": "Plate",
    "componentFailureMode": "Plate Crack/Leak",
    "equipmentCode": "HEX-PLT-001",
    "failureCode": "F-510",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure Drop, Fluid Crossover, Inspection",
    "aiOrInvestigatorQuestions": "Product crossover? High dP?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection log",
    "rootCauseLogic": "Root: Plate cracked. Contrib: Overpressure. Ruled out: Plates OK."
  },
  {
    "id": 32,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Boilers",
    "subtype": "Water Tube",
    "componentFailureMode": "Tube Rupture",
    "equipmentCode": "BOI-WTR-001",
    "failureCode": "F-300",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Drum Level, Pressure, Inspection",
    "aiOrInvestigatorQuestions": "Drum level drop? Visible leak?",
    "attachmentsEvidenceRequired": "Drum level chart, inspection report",
    "rootCauseLogic": "Root: Tube crack/puncture. Contrib: Scale/corrosion. Ruled out: Tubes OK."
  },
  {
    "id": 33,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Boilers",
    "subtype": "Fire Tube",
    "componentFailureMode": "Soot Buildup",
    "equipmentCode": "BOI-FIR-001",
    "failureCode": "F-310",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Stack Temp, Gas Analysis, Inspection",
    "aiOrInvestigatorQuestions": "High stack temp? CO increase?",
    "attachmentsEvidenceRequired": "Stack temp chart, inspection log",
    "rootCauseLogic": "Root: Soot buildup. Contrib: Poor combustion. Ruled out: Tubes clean."
  },
  {
    "id": 34,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Boilers",
    "subtype": "Fire Tube",
    "componentFailureMode": "Burner Failure",
    "equipmentCode": "BOI-FIR-002",
    "failureCode": "F-311",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Flame Pattern, Gas Pressure, Trip Log",
    "aiOrInvestigatorQuestions": "Trip? No flame? Low gas pressure?",
    "attachmentsEvidenceRequired": "Trip log, inspection report",
    "rootCauseLogic": "Root: Burner failed. Contrib: Blocked nozzle. Ruled out: Burner works."
  },
  {
    "id": 35,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Tanks",
    "subtype": "Atmospheric",
    "componentFailureMode": "Roof Corrosion/Leak",
    "equipmentCode": "TNK-ATM-001",
    "failureCode": "F-400",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Level, Roof Movement, Inspection",
    "aiOrInvestigatorQuestions": "Any leak or corrosion? Roof deformation?",
    "attachmentsEvidenceRequired": "Inspection photo, level chart",
    "rootCauseLogic": "Root: Severe corrosion. Contrib: Poor coating. Ruled out: Roof OK."
  },
  {
    "id": 36,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Tanks",
    "subtype": "Pressurized",
    "componentFailureMode": "Shell Crack",
    "equipmentCode": "TNK-PRS-001",
    "failureCode": "F-410",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure, Shell Temp, UT Scan",
    "aiOrInvestigatorQuestions": "UT scan abnormal? Crack observed?",
    "attachmentsEvidenceRequired": "UT scan, pressure chart",
    "rootCauseLogic": "Root: Crack detected. Contrib: Overpressure. Ruled out: Shell OK."
  },
  {
    "id": 37,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Columns/Towers",
    "subtype": "Distillation",
    "componentFailureMode": "Tray Damage/Flooding",
    "equipmentCode": "COL-DST-001",
    "failureCode": "F-420",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure Profile, Level, Inspection",
    "aiOrInvestigatorQuestions": "DP increase? Tray sections flooded?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection log",
    "rootCauseLogic": "Root: Tray collapse. Contrib: Overload. Ruled out: Trays OK."
  },
  {
    "id": 38,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Columns/Towers",
    "subtype": "Absorber",
    "componentFailureMode": "Packing Blockage",
    "equipmentCode": "COL-ABS-001",
    "failureCode": "F-421",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Pressure, Flow, Inspection",
    "aiOrInvestigatorQuestions": "Blocked packing? Pressure build-up?",
    "attachmentsEvidenceRequired": "Pressure/flow chart, inspection",
    "rootCauseLogic": "Root: Blocked. Contrib: Poor feed. Ruled out: Free flow."
  },
  {
    "id": 39,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pressure Vessels",
    "subtype": "Separator",
    "componentFailureMode": "Internal Corrosion",
    "equipmentCode": "VES-SEP-001",
    "failureCode": "F-700",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "UT Scan, Inspection, Corrosion Rate",
    "aiOrInvestigatorQuestions": "Thinning in scan? Pitting found?",
    "attachmentsEvidenceRequired": "UT report, inspection log",
    "rootCauseLogic": "Root: Internal corrosion. Contrib: Chemistry. Ruled out: No corrosion."
  },
  {
    "id": 40,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pressure Vessels",
    "subtype": "Reactor",
    "componentFailureMode": "Nozzle Crack",
    "equipmentCode": "VES-REC-001",
    "failureCode": "F-710",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Inspection, UT, Stress Analysis",
    "aiOrInvestigatorQuestions": "Crack found? Stress concentrations?",
    "attachmentsEvidenceRequired": "Inspection photo, UT chart",
    "rootCauseLogic": "Root: Crack observed. Contrib: Vibration. Ruled out: No defect."
  },
  {
    "id": 41,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Piping",
    "subtype": "Process",
    "componentFailureMode": "External Corrosion",
    "equipmentCode": "PIP-PRS-001",
    "failureCode": "F-800",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "UT Thickness, Visual Insp., Leak Detect.",
    "aiOrInvestigatorQuestions": "Wall loss detected? Leak or pitting?",
    "attachmentsEvidenceRequired": "UT scan, inspection photo",
    "rootCauseLogic": "Root: Coating failure. Contrib: Poor drainage. Ruled out: No wall loss."
  },
  {
    "id": 42,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Piping",
    "subtype": "Process",
    "componentFailureMode": "Internal Erosion",
    "equipmentCode": "PIP-PRS-002",
    "failureCode": "F-801",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Flow Rate, UT, Inspection",
    "aiOrInvestigatorQuestions": "Localized thinning at bends?",
    "attachmentsEvidenceRequired": "UT scan, inspection log",
    "rootCauseLogic": "Root: High velocity/solids. Contrib: Process upset. Ruled out: No thinning."
  },
  {
    "id": 43,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Piping",
    "subtype": "Process",
    "componentFailureMode": "Fatigue Crack",
    "equipmentCode": "PIP-PRS-003",
    "failureCode": "F-802",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Stress Calc, Visual Insp.",
    "aiOrInvestigatorQuestions": "Repetitive vibration? Crack in weld?",
    "attachmentsEvidenceRequired": "Vibration plot, inspection photo",
    "rootCauseLogic": "Root: Vibration/stress. Contrib: Poor support. Ruled out: No defect."
  },
  {
    "id": 44,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Piping",
    "subtype": "DATABASE_DRIVEN",
    "componentFailureMode": "Freeze Damage",
    "equipmentCode": "PIP-UTL-001",
    "failureCode": "F-803",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Temp Data, Weather Log",
    "aiOrInvestigatorQuestions": "Freezing event? Pipe split?",
    "attachmentsEvidenceRequired": "Temp log, inspection report",
    "rootCauseLogic": "Root: Insulation loss. Contrib: Poor tracing. Ruled out: No freeze."
  },
  {
    "id": 45,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Piping",
    "subtype": "Steam",
    "componentFailureMode": "Expansion Joint Failure",
    "equipmentCode": "PIP-STM-001",
    "failureCode": "F-804",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Movement Trend, Inspection",
    "aiOrInvestigatorQuestions": "No movement/failure in joint?",
    "attachmentsEvidenceRequired": "Movement log, inspection",
    "rootCauseLogic": "Root: Joint failed. Contrib: Overtravel. Ruled out: Joint intact."
  },
  {
    "id": 46,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Switchgear",
    "subtype": "MV/LV",
    "componentFailureMode": "Breaker Fails to Open",
    "equipmentCode": "SWG-MV-001",
    "failureCode": "F-1000",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Trip Log, Voltage, Current, IR Scan",
    "aiOrInvestigatorQuestions": "Failed trip event? Relay action?",
    "attachmentsEvidenceRequired": "Trip log, relay report, IR scan",
    "rootCauseLogic": "Root: Trip fail. Contrib: Relay issue. Ruled out: Breaker trips."
  },
  {
    "id": 47,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Switchgear",
    "subtype": "MV/LV",
    "componentFailureMode": "Contact Overheating",
    "equipmentCode": "SWG-MV-002",
    "failureCode": "F-1001",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Temp, Current, IR Scan",
    "aiOrInvestigatorQuestions": "Hotspot on IR? Overcurrent?",
    "attachmentsEvidenceRequired": "IR image, current log",
    "rootCauseLogic": "Root: Loose/burnt contact. Contrib: Overload. Ruled out: No hot spot."
  },
  {
    "id": 48,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Switchgear",
    "subtype": "GIS",
    "componentFailureMode": "SF6 Leak",
    "equipmentCode": "SWG-GIS-001",
    "failureCode": "F-1002",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "SF6 Pressure, Alarm, Inspection",
    "aiOrInvestigatorQuestions": "Low SF6 alarm? Leak visible?",
    "attachmentsEvidenceRequired": "Alarm log, inspection report",
    "rootCauseLogic": "Root: Seal/gasket failure. Contrib: Vibration. Ruled out: Pressure normal."
  },
  {
    "id": 49,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Motors",
    "subtype": "Induction",
    "componentFailureMode": "Winding Insulation Fail",
    "equipmentCode": "MOT-IND-001",
    "failureCode": "F-1400",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "IR Test, Winding Temp, Alarm Log",
    "aiOrInvestigatorQuestions": "IR test fail? Overtemp? Trips?",
    "attachmentsEvidenceRequired": "IR report, temp chart, trip log",
    "rootCauseLogic": "Root: Insulation fail. Contrib: Overload, moisture. Ruled out: IR OK."
  },
  {
    "id": 50,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Motors",
    "subtype": "Induction",
    "componentFailureMode": "Rotor Bar Crack",
    "equipmentCode": "MOT-IND-002",
    "failureCode": "F-1401",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Vibration, Current, Inspection",
    "aiOrInvestigatorQuestions": "Noise? Abnormal current? Inspection result?",
    "attachmentsEvidenceRequired": "Vibration plot, current log, inspection",
    "rootCauseLogic": "Root: Rotor cracked. Contrib: Overload. Ruled out: Rotor OK."
  },
  {
    "id": 51,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Motors",
    "subtype": "Synchronous",
    "componentFailureMode": "Out-of-Step/Sync",
    "equipmentCode": "MOT-SYN-001",
    "failureCode": "F-1402",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Rotor Angle, Current, Alarm Log",
    "aiOrInvestigatorQuestions": "Sync lost? Alarm triggered?",
    "attachmentsEvidenceRequired": "Angle log, alarm report",
    "rootCauseLogic": "Root: Excitation fault. Contrib: Overload. Ruled out: Sync stable."
  },
  {
    "id": 52,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Generators",
    "subtype": "Synchronous",
    "componentFailureMode": "Rotor Earth Fault",
    "equipmentCode": "GEN-SYN-001",
    "failureCode": "F-1500",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Earth Fault Relay, Rotor Voltage, IR Test",
    "aiOrInvestigatorQuestions": "Relay tripped? IR low?",
    "attachmentsEvidenceRequired": "Relay log, IR report",
    "rootCauseLogic": "Root: Insulation fail. Contrib: Moisture. Ruled out: IR normal."
  },
  {
    "id": 53,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Generators",
    "subtype": "Synchronous",
    "componentFailureMode": "Bearing Overheating",
    "equipmentCode": "GEN-SYN-002",
    "failureCode": "F-1501",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Bearing Temp, Vibration",
    "aiOrInvestigatorQuestions": "Temp spike? Vibration up?",
    "attachmentsEvidenceRequired": "Temp chart, vibration plot",
    "rootCauseLogic": "Root: Lube failure. Contrib: Overload. Ruled out: Temp/vib normal."
  },
  {
    "id": 54,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Transmitters",
    "subtype": "Pressure",
    "componentFailureMode": "Calibration Drift",
    "equipmentCode": "INS-PRS-001",
    "failureCode": "F-1600",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output Signal, Calibration Log",
    "aiOrInvestigatorQuestions": "Output drifted? Calibration failed?",
    "attachmentsEvidenceRequired": "Signal chart, calibration record",
    "rootCauseLogic": "Root: Drift confirmed. Contrib: Age. Ruled out: Cal OK."
  },
  {
    "id": 55,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Transmitters",
    "subtype": "Temp",
    "componentFailureMode": "Sensor Burnout",
    "equipmentCode": "INS-TMP-001",
    "failureCode": "F-1601",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Output Signal, Alarm, Inspection",
    "aiOrInvestigatorQuestions": "No signal? Alarm triggered?",
    "attachmentsEvidenceRequired": "Signal log, inspection report",
    "rootCauseLogic": "Root: Sensor burnt. Contrib: Overtemp. Ruled out: Sensor OK."
  },
  {
    "id": 56,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "PLCs/DCS",
    "subtype": "Redundant",
    "componentFailureMode": "CPU Failover",
    "equipmentCode": "SYS-DCS-001",
    "failureCode": "F-1700",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "CPU Status, Alarm Log, Event Log",
    "aiOrInvestigatorQuestions": "Failover occurred? Alarm active?",
    "attachmentsEvidenceRequired": "Alarm log, event log",
    "rootCauseLogic": "Root: CPU failed. Contrib: Power loss. Ruled out: No failover."
  },
  {
    "id": 57,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "PLCs/DCS",
    "subtype": "Non-Redundant",
    "componentFailureMode": "I/O Module Failure",
    "equipmentCode": "SYS-DCS-002",
    "failureCode": "F-1701",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Module Alarm, Signal Status, Event Log",
    "aiOrInvestigatorQuestions": "I/O loss? Module alarm?",
    "attachmentsEvidenceRequired": "Alarm/event log, inspection",
    "rootCauseLogic": "Root: I/O failed. Contrib: Power, surge. Ruled out: Module healthy."
  },
  {
    "id": 58,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Pneumatic",
    "componentFailureMode": "Stem Stiction",
    "equipmentCode": "CVL-PNU-001",
    "failureCode": "F-1800",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Stem Position, Control Signal, Test",
    "aiOrInvestigatorQuestions": "Stem slow/stuck? Hysteresis observed?",
    "attachmentsEvidenceRequired": "Position log, signal chart, test report",
    "rootCauseLogic": "Root: Stiction. Contrib: Seal age. Ruled out: Smooth motion."
  },
  {
    "id": 59,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Electric",
    "componentFailureMode": "Motor Burnout",
    "equipmentCode": "CVL-ELC-001",
    "failureCode": "F-1801",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Motor Current, Temp, Alarm Log",
    "aiOrInvestigatorQuestions": "High current? Motor hot? Burnt smell?",
    "attachmentsEvidenceRequired": "Current log, temp chart, alarm report",
    "rootCauseLogic": "Root: Motor burnt. Contrib: Overload. Ruled out: Current/Temp normal."
  },
  {
    "id": 60,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Gas Chromatograph",
    "componentFailureMode": "Calibration Drift",
    "equipmentCode": "ANA-GC-001",
    "failureCode": "F-1900",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output Signal, Cal. Log, Validation Report",
    "aiOrInvestigatorQuestions": "Reading drifted? Calibration overdue?",
    "attachmentsEvidenceRequired": "Output trend, calibration log, validation",
    "rootCauseLogic": "Root: Drift confirmed. Contrib: Standard aging. Ruled out: Cal OK."
  },
  {
    "id": 61,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Gas Chromatograph",
    "componentFailureMode": "Valve Sticking",
    "equipmentCode": "ANA-GC-002",
    "failureCode": "F-1901",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Event Log, Chromatogram, Inspection",
    "aiOrInvestigatorQuestions": "Abnormal peak shape? Valve error in log?",
    "attachmentsEvidenceRequired": "Chromatogram, event log, inspection",
    "rootCauseLogic": "Root: Valve stuck. Contrib: Contaminant. Ruled out: No errors."
  },
  {
    "id": 62,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "pH Analyzer",
    "componentFailureMode": "Sensor Coating/Poisoning",
    "equipmentCode": "ANA-PH-001",
    "failureCode": "F-1910",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output, Calibration Log, Inspection",
    "aiOrInvestigatorQuestions": "Reading stable? Cleaning performed?",
    "attachmentsEvidenceRequired": "Output trend, calibration/cleaning log",
    "rootCauseLogic": "Root: Coated sensor. Contrib: No cleaning. Ruled out: Sensor clear."
  },
  {
    "id": 63,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Conductivity Analyzer",
    "componentFailureMode": "Cell Fouling",
    "equipmentCode": "ANA-CND-001",
    "failureCode": "F-1920",
    "riskRanking": "Low",
    "requiredTrendDataEvidence": "Output, Inspection, Cleaning Log",
    "aiOrInvestigatorQuestions": "Output erratic? Fouling in cell?",
    "attachmentsEvidenceRequired": "Output trend, cleaning log, inspection",
    "rootCauseLogic": "Root: Fouling confirmed. Contrib: High solids. Ruled out: Clean cell."
  },
  {
    "id": 64,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Moisture Analyzer",
    "componentFailureMode": "Probe Aging",
    "equipmentCode": "ANA-MOI-001",
    "failureCode": "F-1930",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output, Calibration, Validation",
    "aiOrInvestigatorQuestions": "Slow response? Sensor age >2 years?",
    "attachmentsEvidenceRequired": "Output trend, calibration log, replacement",
    "rootCauseLogic": "Root: Aged probe. Contrib: Harsh service. Ruled ou"
  },
  {
    "id": 65,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "HVAC Units",
    "subtype": "Chiller",
    "componentFailureMode": "Refrigerant Leak",
    "equipmentCode": "HVAC-CHL-001",
    "failureCode": "F-2000",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Temp, Pressure, Refrigerant Level",
    "aiOrInvestigatorQuestions": "Pressure drop? Visual leak?",
    "attachmentsEvidenceRequired": "Pressure chart, leak report",
    "rootCauseLogic": "Root: Leak confirmed. Contrib: Seal/O-ring. Ruled out: No leak."
  },
  {
    "id": 66,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "HVAC Units",
    "subtype": "Air Handler",
    "componentFailureMode": "Filter Blockage",
    "equipmentCode": "HVAC-AHU-001",
    "failureCode": "F-2010",
    "riskRanking": "Low",
    "requiredTrendDataEvidence": "Pressure Drop, Flow, Inspection",
    "aiOrInvestigatorQuestions": "High dP? Reduced flow? Dirty filter?",
    "attachmentsEvidenceRequired": "Pressure drop chart, inspection log",
    "rootCauseLogic": "Root: Blocked filter. Contrib: No replacement. Ruled out: Clean filter."
  },
  {
    "id": 67,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "HVAC Units",
    "subtype": "Split",
    "componentFailureMode": "Compressor Overload",
    "equipmentCode": "HVAC-SPL-001",
    "failureCode": "F-2020",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Current, Temp, Alarm Log",
    "aiOrInvestigatorQuestions": "Compressor trip? Current spike?",
    "attachmentsEvidenceRequired": "Current log, alarm report",
    "rootCauseLogic": "Root: Overload. Contrib: Low refrigerant. Ruled out: Normal run."
  },
  {
    "id": 68,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "HVAC Units",
    "subtype": "Chiller",
    "componentFailureMode": "Evaporator Freeze",
    "equipmentCode": "HVAC-CHL-002",
    "failureCode": "F-2001",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Temp, Flow, Alarm Log",
    "aiOrInvestigatorQuestions": "Evap temp below zero? Alarm triggered?",
    "attachmentsEvidenceRequired": "Temp chart, alarm log",
    "rootCauseLogic": "Root: Freeze confirmed. Contrib: Flow loss. Ruled out: Temp normal."
  },
  {
    "id": 69,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cranes/Hoists",
    "subtype": "Bridge",
    "componentFailureMode": "Brake Failure",
    "equipmentCode": "CRA-BRG-001",
    "failureCode": "F-2100",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Brake Temp, Motor Current, Load, Insp.",
    "aiOrInvestigatorQuestions": "Brakes slip? Temp high? Uncontrolled movement?",
    "attachmentsEvidenceRequired": "Temp chart, brake insp. report",
    "rootCauseLogic": "Root: Worn/faulty brake. Contrib: Overload. Ruled out: Brake works."
  },
  {
    "id": 70,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cranes/Hoists",
    "subtype": "Gantry",
    "componentFailureMode": "Limit Switch Failure",
    "equipmentCode": "CRA-GAN-001",
    "failureCode": "F-2110",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Switch Status, Event Log",
    "aiOrInvestigatorQuestions": "Travel overrun? Limit switch log?",
    "attachmentsEvidenceRequired": "Switch status, event log",
    "rootCauseLogic": "Root: Switch failed. Contrib: Wiring. Ruled out: Switch operates."
  },
  {
    "id": 71,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cranes/Hoists",
    "subtype": "Jib",
    "componentFailureMode": "Wire Rope Wear/Break",
    "equipmentCode": "CRA-JIB-001",
    "failureCode": "F-2120",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Rope Insp., Load Test, Operation Log",
    "aiOrInvestigatorQuestions": "Rope broken? Visible wear?",
    "attachmentsEvidenceRequired": "Inspection report, load test",
    "rootCauseLogic": "Root: Rope failed. Contrib: Overload, lube. Ruled out: Rope OK."
  },
  {
    "id": 72,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cranes/Hoists",
    "subtype": "All",
    "componentFailureMode": "Overload Protection Fail",
    "equipmentCode": "CRA-ALL-001",
    "failureCode": "F-2130",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Load Cell, Event Log, Alarm",
    "aiOrInvestigatorQuestions": "Overload not detected? Alarmed?",
    "attachmentsEvidenceRequired": "Load cell record, alarm/event log",
    "rootCauseLogic": "Root: Protection bypassed/failed. Contrib: Setpoint error. Ruled out: Protection OK."
  },
  {
    "id": 73,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fire Protection Systems",
    "subtype": "Deluge",
    "componentFailureMode": "Valve WonÃt Open",
    "equipmentCode": "FPS-DLG-001",
    "failureCode": "F-2200",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Actuation Log, Water Pressure, Insp.",
    "aiOrInvestigatorQuestions": "No flow at test? Actuation fail log?",
    "attachmentsEvidenceRequired": "Actuation log, pressure chart, inspection",
    "rootCauseLogic": "Root: Valve seized. Contrib: Corrosion, dirt. Ruled out: Operates OK."
  },
  {
    "id": 74,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fire Protection Systems",
    "subtype": "Sprinkler",
    "componentFailureMode": "Plugged Head",
    "equipmentCode": "FPS-SPR-001",
    "failureCode": "F-2210",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Flow Test, Insp., Head Check",
    "aiOrInvestigatorQuestions": "Flow reduced at head? Debris in head?",
    "attachmentsEvidenceRequired": "Flow test log, inspection report",
    "rootCauseLogic": "Root: Plugged. Contrib: No flushing. Ruled out: Head clear."
  },
  {
    "id": 75,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fire Protection Systems",
    "subtype": "Alarm Panel",
    "componentFailureMode": "Battery Backup Fail",
    "equipmentCode": "FPS-ALM-001",
    "failureCode": "F-2220",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Battery Voltage, Alarm Log, Insp.",
    "aiOrInvestigatorQuestions": "Low voltage? Alarm fail on power loss?",
    "attachmentsEvidenceRequired": "Battery log, alarm log, inspection",
    "rootCauseLogic": "Root: Battery failed. Contrib: Age. Ruled out: Battery OK."
  },
  {
    "id": 76,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Fire Protection Systems",
    "subtype": "Hydrant",
    "componentFailureMode": "Low Pressure",
    "equipmentCode": "FPS-HYD-001",
    "failureCode": "F-2230",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pressure Analysis, Inspection",
    "aiOrInvestigatorQuestions": "Hydrant flow low? Leak in system?",
    "attachmentsEvidenceRequired": "Pressure chart, inspection report",
    "rootCauseLogic": "Root: Low supply/valve issue. Contrib: Main line leak. Ruled out: Normal pressure."
  },
  {
    "id": 77,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "TOC (Total Organic C)",
    "componentFailureMode": "Reagent Pump Failure",
    "equipmentCode": "ANA-TOC-001",
    "failureCode": "F-1950",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Pump Flow, Alarm Log, Insp.",
    "aiOrInvestigatorQuestions": "Flow loss? Alarm active?",
    "attachmentsEvidenceRequired": "Pump log, alarm log, inspection",
    "rootCauseLogic": "Root: Pump stopped. Contrib: Blockage. Ruled out: Pump works."
  },
  {
    "id": 78,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "TOC",
    "componentFailureMode": "Detector Lamp Out",
    "equipmentCode": "ANA-TOC-002",
    "failureCode": "F-1951",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output Signal, Lamp Hours, Insp.",
    "aiOrInvestigatorQuestions": "No output? Lamp time > limit?",
    "attachmentsEvidenceRequired": "Output log, lamp hour record, inspection",
    "rootCauseLogic": "Root: Lamp dead. Contrib: Old lamp. Ruled out: Lamp replaced."
  },
  {
    "id": 79,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "O2 Analyzer",
    "componentFailureMode": "Sensor Aging",
    "equipmentCode": "ANA-O2-001",
    "failureCode": "F-1960",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "O2 Output, Calibration Log",
    "aiOrInvestigatorQuestions": "Output drifted? Sensor overage?",
    "attachmentsEvidenceRequired": "Output trend, calibration log, replacement",
    "rootCauseLogic": "Root: Aged sensor. Contrib: High O2/humidity. Ruled out: New sensor."
  },
  {
    "id": 80,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Stack Emission",
    "componentFailureMode": "Sample Line Plugged",
    "equipmentCode": "ANA-STA-001",
    "failureCode": "F-1970",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Flow, Pressure, Inspection",
    "aiOrInvestigatorQuestions": "No flow? Pressure up? Inspection confirms blockage?",
    "attachmentsEvidenceRequired": "Flow/pressure log, inspection",
    "rootCauseLogic": "Root: Plugged. Contrib: Poor heating. Ruled out: Line clear."
  },
  {
    "id": 81,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Analyzers",
    "subtype": "Stack Emission",
    "componentFailureMode": "Dilution Air Loss",
    "equipmentCode": "ANA-STA-002",
    "failureCode": "F-1971",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Dilution Air Pressure, Flow, Alarm",
    "aiOrInvestigatorQuestions": "Low dilution air? Alarm active?",
    "attachmentsEvidenceRequired": "Pressure/flow log, alarm log",
    "rootCauseLogic": "Root: Air lost. Contrib: Compressor trip. Ruled out: Air stable."
  },
  {
    "id": 82,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Chemical Injection",
    "subtype": "Skid",
    "componentFailureMode": "Pump Failure",
    "equipmentCode": "CHM-SKD-001",
    "failureCode": "F-2500",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Pump Flow, Alarm Log, Inspection",
    "aiOrInvestigatorQuestions": "No injection? Pump alarm?",
    "attachmentsEvidenceRequired": "Flow log, alarm log, inspection",
    "rootCauseLogic": "Root: Pump fail. Contrib: Jammed head. Ruled out: Pump works."
  },
  {
    "id": 83,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Chemical Injection",
    "subtype": "Skid",
    "componentFailureMode": "Flowmeter Drift",
    "equipmentCode": "CHM-SKD-002",
    "failureCode": "F-2501",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Output, Calibration Log",
    "aiOrInvestigatorQuestions": "Output error? Calibration overdue?",
    "attachmentsEvidenceRequired": "Output chart, calibration log",
    "rootCauseLogic": "Root: Drift confirmed. Contrib: Fluid deposit. Ruled out: Meter ok."
  },
  {
    "id": 84,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cooling Tower",
    "subtype": "Forced Draft",
    "componentFailureMode": "Fan Motor Overload",
    "equipmentCode": "CLT-FOR-001",
    "failureCode": "F-2510",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Motor Current, Temp, Alarm Log",
    "aiOrInvestigatorQuestions": "Overload trip? Current spike?",
    "attachmentsEvidenceRequired": "Current log, temp chart, alarm log",
    "rootCauseLogic": "Root: Overload. Contrib: Blocked airflow. Ruled out: Normal run."
  },
  {
    "id": 85,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cooling Tower",
    "subtype": "Forced Draft",
    "componentFailureMode": "Water Distribution Blockage",
    "equipmentCode": "CLT-FOR-002",
    "failureCode": "F-2511",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Flow, Inspection, Alarm Log",
    "aiOrInvestigatorQuestions": "Reduced flow? Spray blocked?",
    "attachmentsEvidenceRequired": "Flow chart, inspection report",
    "rootCauseLogic": "Root: Blocked. Contrib: Scale. Ruled out: Even flow."
  },
  {
    "id": 86,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Cooling Tower",
    "subtype": "Induced Draft",
    "componentFailureMode": "Drift Eliminator Loss",
    "equipmentCode": "CLT-IND-001",
    "failureCode": "F-2512",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Blowdown Rate, Inspection",
    "aiOrInvestigatorQuestions": "Water carryover? Eliminator missing/damaged?",
    "attachmentsEvidenceRequired": "Blowdown log, inspection report",
    "rootCauseLogic": "Root: Eliminator loss. Contrib: Wind. Ruled out: Intact."
  },
  {
    "id": 87,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Gearboxes",
    "subtype": "Parallel Shaft",
    "componentFailureMode": "Tooth Wear/Breakage",
    "equipmentCode": "GBX-PSH-001",
    "failureCode": "F-2600",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Oil Debris, Temp",
    "aiOrInvestigatorQuestions": "Vibration spike? Debris in oil? Temp up?",
    "attachmentsEvidenceRequired": "Vibration plot, oil sample, temp log",
    "rootCauseLogic": "Root: Gear worn/broken. Contrib: Lube loss. Ruled out: No wear."
  },
  {
    "id": 88,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Gearboxes",
    "subtype": "Planetary",
    "componentFailureMode": "Carrier Bearing Failure",
    "equipmentCode": "GBX-PLN-001",
    "failureCode": "F-2601",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Bearing Temp, Oil Analysis",
    "aiOrInvestigatorQuestions": "Bearing temp high? Vibration up?",
    "attachmentsEvidenceRequired": "Temp chart, oil analysis, vibration plot",
    "rootCauseLogic": "Root: Bearing fail. Contrib: Contaminant. Ruled out: Bearing OK."
  },
  {
    "id": 89,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Expanders",
    "subtype": "Turbo-Expander",
    "componentFailureMode": "Rotor Rub",
    "equipmentCode": "EXP-TUR-001",
    "failureCode": "F-2700",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Rotor Position, Temp",
    "aiOrInvestigatorQuestions": "Rub event? Position shift? Temp spike?",
    "attachmentsEvidenceRequired": "Vibration chart, rotor pos., temp chart",
    "rootCauseLogic": "Root: Rub confirmed. Contrib: Surge. Ruled out: Centered."
  },
  {
    "id": 90,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Expanders",
    "subtype": "Turbo-Expander",
    "componentFailureMode": "Shaft Seal Leak",
    "equipmentCode": "EXP-TUR-002",
    "failureCode": "F-2701",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Seal Pot Level, Pressure, Insp.",
    "aiOrInvestigatorQuestions": "Seal level low? Leak seen?",
    "attachmentsEvidenceRequired": "Seal pot log, inspection photo",
    "rootCauseLogic": "Root: Seal leak. Contrib: Age, misalignment. Ruled out: Seal new."
  },
  {
    "id": 91,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Effluent System",
    "subtype": "Clarifier",
    "componentFailureMode": "Rake Drive Failure",
    "equipmentCode": "EFF-CLR-001",
    "failureCode": "F-2800",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Drive Current, Load, Insp.",
    "aiOrInvestigatorQuestions": "No rotation? High current?",
    "attachmentsEvidenceRequired": "Current log, load chart, inspection report",
    "rootCauseLogic": "Root: Jammed drive. Contrib: Debris. Ruled out: Smooth drive."
  },
  {
    "id": 92,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Effluent System",
    "subtype": "Clarifier",
    "componentFailureMode": "Sludge Pump Blockage",
    "equipmentCode": "EFF-CLR-002",
    "failureCode": "F-2801",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Flow, Pressure, Alarm",
    "aiOrInvestigatorQuestions": "Pump off? Low flow? Blockage?",
    "attachmentsEvidenceRequired": "Flow chart, alarm log, inspection report",
    "rootCauseLogic": "Root: Blockage. Contrib: Fibrous solids. Ruled out: Pump runs free."
  },
  {
    "id": 93,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Plant Air",
    "componentFailureMode": "Dryer Malfunction",
    "equipmentCode": "UTL-AIR-001",
    "failureCode": "F-2900",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Dew Point, Pressure, Alarm",
    "aiOrInvestigatorQuestions": "Dew point rise? Pressure drop?",
    "attachmentsEvidenceRequired": "Dew point trend, alarm log",
    "rootCauseLogic": "Root: Dryer failed. Contrib: Heater fail. Ruled out: Dew point normal."
  },
  {
    "id": 94,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Potable Water",
    "componentFailureMode": "Chlorine Dose Loss",
    "equipmentCode": "UTL-WTR-001",
    "failureCode": "F-2910",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Residual Test, Flow, Alarm",
    "aiOrInvestigatorQuestions": "Low chlorine? Alarm triggered?",
    "attachmentsEvidenceRequired": "Residual chart, alarm log",
    "rootCauseLogic": "Root: Dose pump fail. Contrib: Empty chem. Ruled out: Pump working."
  },
  {
    "id": 95,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Stack",
    "componentFailureMode": "CEMS Analyzer Out of Service",
    "equipmentCode": "ENV-STK-001",
    "failureCode": "F-2920",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Status, Alarm, Insp.",
    "aiOrInvestigatorQuestions": "Out of service? Alarm?",
    "attachmentsEvidenceRequired": "Status log, alarm, inspection report",
    "rootCauseLogic": "Root: Analyzer fail. Contrib: Power loss. Ruled out: Analyzer online."
  },
  {
    "id": 96,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "DATABASE_DRIVEN",
    "subtype": "Sump",
    "componentFailureMode": "Level High/Overflow",
    "equipmentCode": "ENV-SMP-001",
    "failureCode": "F-2925",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Level Trend, Pump Status, Alarm",
    "aiOrInvestigatorQuestions": "Level high? Pump running?",
    "attachmentsEvidenceRequired": "Level trend, pump status, alarm log",
    "rootCauseLogic": "Root: Pump fail/high inflow. Contrib: Blockage. Ruled out: Level normal."
  },
  {
    "id": 97,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Shaft Misalignment",
    "equipmentCode": "PMP-CEN-006",
    "failureCode": "F-006",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Vibration, Laser Alignment Report",
    "aiOrInvestigatorQuestions": "Is misalignment confirmed? Any prior alignment issues?",
    "attachmentsEvidenceRequired": "Vibration spectrum, alignment report",
    "rootCauseLogic": "Root: Misalignment. Contrib: Thermal growth, installation error."
  },
  {
    "id": 98,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Shaft Breakage",
    "equipmentCode": "PMP-CEN-007",
    "failureCode": "F-007",
    "riskRanking": "Critical",
    "requiredTrendDataEvidence": "Torque data, Overload trend, Metallurgy",
    "aiOrInvestigatorQuestions": "When did break occur? Was there sudden overload?",
    "attachmentsEvidenceRequired": "Broken shaft image, metallurgical report",
    "rootCauseLogic": "Root: Shaft fatigue. Contrib: Overload, cyclic stress, defects."
  },
  {
    "id": 99,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Shaft Key Shear",
    "equipmentCode": "PMP-CEN-008",
    "failureCode": "F-008",
    "riskRanking": "Medium",
    "requiredTrendDataEvidence": "Torque spike, Shaft coupling inspection",
    "aiOrInvestigatorQuestions": "Was torque spike observed? Was key worn out?",
    "attachmentsEvidenceRequired": "Inspection photo, torque log",
    "rootCauseLogic": "Root: Key shear. Contrib: Improper key fit, cyclic load."
  },
  {
    "id": 100,
    "equipmentGroup": "DATABASE_DRIVEN",
    "equipmentType": "Pumps",
    "subtype": "Centrifugal",
    "componentFailureMode": "Shaft Not Available (Spare)",
    "equipmentCode": "PMP-CEN-009",
    "failureCode": "F-009",
    "riskRanking": "High",
    "requiredTrendDataEvidence": "Inventory logs, Procurement data",
    "aiOrInvestigatorQuestions": "Was the spare ordered/stored? Any logistic delays?",
    "attachmentsEvidenceRequired": "Procurement trail, inventory report",
    "rootCauseLogic": "Root: Spare not available. Contrib: Inventory gap, poor planning."
  }
];

export async function loadEvidenceLibraryData() {
  return EVIDENCE_LIBRARY_DATA;
}